# Generated by Django 5.1.4 on 2025-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='level',
            field=models.CharField(default='Advanced', max_length=50),
            preserve_default=False,
        ),
    ]
