# Generated by Django 5.1.4 on 2025-06-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_service_topic1_service_topic10_service_topic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='left',
            field=models.ImageField(default='evr', upload_to='head/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='head',
            name='right',
            field=models.ImageField(default='rv', upload_to='head/'),
            preserve_default=False,
        ),
    ]
