# Generated by Django 5.1.4 on 2025-06-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_mentor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mentor',
            new_name='Mentor_image',
        ),
    ]
